server:
  port: ${PORT:8080}

config:
  telegram_bot_token: ${TELEGRAM_BOT_TOKEN:no-telegram-bot-token}
  camera_service_url: ${CAMERA_SERVICE_URL:no-camera-service-url}
  base_url: ${BASE_URL:no-base-url}

